apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-peuzuy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-peuzuy
  namespace: my-nginx-peuzuy
  labels:
    name: nginx-peuzuy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-peuzuy
  template:
    metadata:
      namespace: my-nginx-peuzuy
      labels:
        name: nginx-peuzuy
    spec:
      containers:
      - name: nginx-peuzuy
        image: nginx
        ports:
        - containerPort: 80

